### ISSUE TITLE
app stopped working

### ISSUE THREAD

**Issue by GhostTalker** [5310/discord-bot-castform#19] opened 2021-05-25 23:59 UTC
npm start

> discord-bot-castform@2.2.0 start
> node index.js

/srv/PogoWeather/model-ajstewart.js:172
  const weather = weatherMap[label] ?? { dominant: 'unknown', superficial: {}, windyable: false }
                                     ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/srv/PogoWeather/index.js:35:22)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

**Comment by 5310** [comment] 2021-05-26 05:57
Upgrade your version of Node, please. This is a duplicate of #18

**Closed as completed by 5310** 2021-05-26 05:57 UTC
